// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.API.DBConnector;

namespace TicketSystem.API.Migrations
{
    [DbContext(typeof(TicketSystemDbContext))]
    partial class TicketSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketSystem.API.Entities.AgentEntity", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("agent_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentName")
                        .HasColumnName("agent_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgentId");

                    b.ToTable("agent","ticket_system_db");

                    b.HasData(
                        new
                        {
                            AgentId = new Guid("6ce2c411-1fc8-4f2f-9f8b-37a2ed025f55"),
                            AgentName = "Agent 2dc7f6a4-fc42-437b-83ac-3af6e8dcc06d"
                        },
                        new
                        {
                            AgentId = new Guid("4d17bbb8-bf62-4761-a5ea-9cc98ad246d2"),
                            AgentName = "Agent f47a2f90-4d0f-4421-b30a-a3dadf7012ff"
                        });
                });

            modelBuilder.Entity("TicketSystem.API.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnName("agent_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentName")
                        .HasColumnName("agent_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAssigned")
                        .HasColumnName("is_assigned")
                        .HasColumnType("bit");

                    b.Property<string>("UserType")
                        .HasColumnName("user_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("user","ticket_system_db");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b9e810e-5416-4c70-bdf4-7e05b58babca"),
                            AgentId = new Guid("c0cb0301-33d8-42b1-9fd6-65a20270b3a9"),
                            AgentName = "Agent fcf539f6-263c-4ec7-a6d2-2b282f8546af",
                            Email = "a@gmail.com",
                            IsAssigned = true,
                            UserType = "Customer"
                        },
                        new
                        {
                            Id = new Guid("46636628-40e2-4412-821d-94bc9515a2f4"),
                            AgentId = new Guid("4bed90af-e737-4e11-8676-764a10d6e0be"),
                            AgentName = "Agent 4a0e769c-d3cc-4d17-8097-b30c25a25fb3",
                            Email = "b@gmail.com",
                            IsAssigned = true,
                            UserType = "Customer"
                        },
                        new
                        {
                            Id = new Guid("cd7f9700-c107-48a5-9079-ad289f71238b"),
                            AgentId = new Guid("d5c8bb39-1d25-45a0-b184-e5f6891c860f"),
                            AgentName = "Agent bb4f735e-a88b-426b-bfc3-9d98996762a1",
                            Email = "c@gmail.com",
                            IsAssigned = false,
                            UserType = "Customer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
