USE [master]
GO

/****** Object:  Database [TicketSystemDB]    Script Date: 24-01-2021 19:01:09 ******/
CREATE DATABASE [TicketSystemDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TicketSystemDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TicketSystemDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TicketSystemDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TicketSystemDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TicketSystemDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TicketSystemDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TicketSystemDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TicketSystemDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TicketSystemDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TicketSystemDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TicketSystemDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TicketSystemDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TicketSystemDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TicketSystemDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TicketSystemDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TicketSystemDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TicketSystemDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TicketSystemDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TicketSystemDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TicketSystemDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TicketSystemDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TicketSystemDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TicketSystemDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TicketSystemDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TicketSystemDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TicketSystemDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TicketSystemDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TicketSystemDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TicketSystemDB] SET  MULTI_USER 
GO

ALTER DATABASE [TicketSystemDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TicketSystemDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TicketSystemDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TicketSystemDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TicketSystemDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TicketSystemDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TicketSystemDB] SET  READ_WRITE 
GO


